return {
  require "custom.plugins.copilot",
  require "custom.plugins.lspconfig",
  require "custom.plugins.lspconfig",
  require "custom.plugins.todo-comments",
  require "custom.plugins.php-refactoring",
  require "custom.plugins.discord-presence",
  require "custom.plugins.bible-votd",
  require "custom.plugins.oil",
  require "custom.plugins.vim-tmux-navigator",
  require "custom.plugins.laravel",
  require "custom.plugins.nvim-notify",
  require "custom.plugins.svelte",
  require "custom.plugins.spectre",
  require "custom.plugins.nvim-ts-autotag",
  require "custom.plugins.markdown",

  require "custom.plugins.overrides.nvim-tree",
  require "custom.plugins.overrides.nvim-cmp",
  require "custom.plugins.overrides.nvim-colorizer",
}
